import { getShopflowLocaleCatalog, type UiLocale } from '@shopflow/core';

export function getUiShellCopy(locale: UiLocale = 'en') {
  const catalog = getShopflowLocaleCatalog(locale);

  return {
    brand: catalog.common.brand,
    common: {
      displayLanguageLabel: catalog.common.displayLanguageLabel,
      languageOptionLabels: catalog.common.languageOptionLabels,
      routeOriginLabels: catalog.common.routeOriginLabels,
      jumpToSourcePage: catalog.common.jumpToSourcePage,
      openLatestSourcePage: catalog.common.openLatestSourcePage,
      openLatestCapturedPage: catalog.common.openLatestCapturedPage,
      openSourcePage: catalog.common.openSourcePage,
      openEvidenceSourcePage: catalog.common.openEvidenceSourcePage,
    },
    sidePanel: {
      intro: catalog.sidePanel.introSummary,
      readinessSummary: catalog.sidePanel.readinessSummaryHeading,
      whatThisPageCanDoNow: catalog.sidePanel.whatThisPageCanDoHeading,
      bestRoute: catalog.sidePanel.bestRouteHeading,
      runnableNowHeading: catalog.sidePanel.runnableNowHeading,
      needsAttentionHeading: catalog.sidePanel.needsAttentionHeading,
      claimBoundary: catalog.sidePanel.claimBoundaryHeading,
      operatorNextStep: catalog.sidePanel.operatorNextStepHeading,
      currentSite: catalog.sidePanel.currentSiteHeading,
      availableOnPage: catalog.sidePanel.availableOnThisPageHeading,
      whyUnavailable: catalog.sidePanel.nextStepPrefixInline,
      quickActions: catalog.sidePanel.quickActionsHeading,
      quickActionsIntro: catalog.sidePanel.quickActionsSummary,
      primarySupportedMove: catalog.sidePanel.primarySupportedMove,
      supportedMove: catalog.sidePanel.supportedMove,
      noRunnableCapability: catalog.sidePanel.noRunnableCapability,
      noRunnableCapabilityTail: catalog.sidePanel.blockedPathHonesty,
      primaryRoute: catalog.sidePanel.primaryRouteHeading,
      nextRoute: catalog.sidePanel.nextRouteHeading,
      liveReceiptThreeLayers: catalog.sidePanel.evidenceSystemSummary,
      evidenceOverview: catalog.sidePanel.evidenceOverviewHeading,
      reviewLane: catalog.sidePanel.reviewLaneHeading,
      captureLaneClearSummary: catalog.model.captureLaneClearSummary,
      captureQueueSummary: catalog.model.captureQueueSummary,
      captureInProgressQueueSummary:
        catalog.model.captureInProgressQueueSummary,
      noReviewLaneItems: catalog.model.noReviewLaneItems,
      reviewPendingSummary: catalog.model.reviewPendingSummary,
      reviewedCountSummary: catalog.model.reviewedCountSummary,
      rejectedCountSummary: catalog.model.rejectedCountSummary,
      expiredCountSummary: catalog.model.expiredCountSummary,
      rawPacketLedger: catalog.sidePanel.rawPacketLedgerHeading,
      decisionBrief: catalog.sidePanel.decisionBriefHeading,
      nextAssistantMove: catalog.sidePanel.nextAssistantMove,
      workflowCopilot: catalog.model.workflowCopilotHeading,
      packetPrefix: catalog.sidePanel.packetPrefix,
      updatedPrefix: catalog.sidePanel.updatedPrefix,
      operatorNotePrefix: catalog.sidePanel.operatorNotePrefix,
      latestProofPrefix: catalog.sidePanel.latestProofPrefix,
      reviewPrefix: catalog.sidePanel.reviewPrefix,
      reviewNotePrefix: catalog.sidePanel.reviewNotePrefix,
      recentActivityHeading: catalog.sidePanel.recentActivityHeading,
      nextRoutesHeading: catalog.sidePanel.nextRoutesHeading,
      noVerifiedActivity: catalog.sidePanel.noVerifiedActivity,
      openRoute: catalog.sidePanel.openRoute,
      verifiedScopePrefix: catalog.sidePanel.verifiedScopePrefix,
      bestRouteAria: catalog.sidePanel.bestRouteAria,
      nextRouteAria: catalog.sidePanel.nextRouteAria,
      operatorNextStepAria: catalog.sidePanel.operatorNextStepAria,
      nextStepPrefix: catalog.sidePanel.nextStepPrefix,
      nextStepPrefixInline: catalog.sidePanel.nextStepPrefixInline,
      statusLabels: catalog.sidePanel.statusLabels,
      capabilityStatusLabels: catalog.sidePanel.capabilityStatusLabels,
      countsSummary: catalog.sidePanel.countsSummary,
      sourceCapturedSplitSummary: catalog.sidePanel.sourceCapturedSplitSummary,
    },
    popup: {
      defaultActionHeading: catalog.popup.defaultActionHeading,
      supportingRoutesHeading: catalog.popup.supportingRoutesHeading,
      openSidePanel: catalog.popup.openSidePanel,
      viewCurrentSupportState: catalog.popup.viewCurrentSupportState,
      openSidePanelQuickActions: catalog.popup.openSidePanelQuickActions,
      openSidePanelReadinessSummary:
        catalog.popup.openSidePanelReadinessSummary,
      openSidePanelCaptureQueue: catalog.popup.openSidePanelCaptureQueue,
      openSidePanelReviewLane: catalog.popup.openSidePanelReviewLane,
      openSidePanelRecentActivity: catalog.popup.openSidePanelRecentActivity,
      openSidePanelCurrentSiteSummary:
        catalog.popup.openSidePanelCurrentSiteSummary,
      resumeLatestCapturedPage: catalog.popup.resumeLatestCapturedPage,
      openLatestSourcePage: catalog.popup.openLatestSourcePage,
      openMainSurfaceSummary: catalog.popup.openMainSurfaceSummary,
      openSecondaryRouteSummary: catalog.popup.openSecondaryRouteSummary,
      latestSourceLabel: catalog.popup.latestSourceLabel,
      claimBoundaryPrefix: catalog.popup.claimBoundaryPrefix,
      evidenceQueuePrefix: catalog.popup.evidenceQueuePrefix,
      evidenceNextStepPrefix: catalog.popup.evidenceNextStepPrefix,
      ledgerNote: catalog.popup.ledgerNote,
      nextStepPrefix: catalog.popup.nextStepPrefix,
      recentActivityPrefix: catalog.popup.recentActivityPrefix,
      seenPrefix: catalog.popup.seenPrefix,
      quickRouter: catalog.popup.quickRouterHeading,
      quickRouterIntro: catalog.popup.quickRouterSummary,
      primaryRoute: catalog.popup.primaryRouteHeading,
      secondaryRoute: catalog.popup.secondaryRouteHeading,
      jumpBack: catalog.popup.jumpBackHeading,
      sourceCapturedSplitSummary: catalog.popup.sourceCapturedSplitSummary,
      latestCapturedAt: (timestampLabel: string) =>
        `${catalog.common.capturedAtPrefix} ${timestampLabel}`,
      jumpBackSummary: catalog.popup.jumpBackSummary,
    },
    suite: {
      internalAlphaOnly: catalog.suite.internalAlphaOnly,
      operatorPromise: catalog.suite.operatorPromise,
      startHere: catalog.suite.startHereHeading,
      alphaGuardrails: catalog.suite.alphaGuardrailsHeading,
      priorityRoutes: catalog.suite.priorityRoutesHeading,
      priorityRoutesSummary: catalog.suite.priorityRoutesSummary,
      claimReadinessBoard: catalog.suite.claimReadinessHeading,
      claimReadinessSummary: catalog.suite.claimReadinessSummary,
      currentRolloutMap: catalog.suite.currentRolloutHeading,
      currentRolloutSummary: catalog.suite.currentRolloutSummary,
      openSidePanelRolloutMap: catalog.suite.openSidePanelRolloutMapLabel,
      openSidePanelClaimReadiness:
        catalog.suite.openSidePanelClaimReadinessLabel,
      frontDoorAria: catalog.suite.frontDoorAria,
      operatorNextStepAria: catalog.suite.operatorNextStepAria,
      priorityPacketActionAria: catalog.suite.priorityPacketActionAria,
      openSidePanelFamilyChooser: catalog.suite.openSidePanelFamilyChooserLabel,
      latestDetection: catalog.suite.latestDetectionHeading,
      latestRecentActivity: catalog.suite.latestRecentActivityHeading,
      latestCapturedOutput: catalog.suite.latestCapturedOutputHeading,
      frontDoorForThisApp: catalog.suite.frontDoorHeading,
      evidenceQueue: catalog.suite.evidenceQueueHeading,
      priorityPacket: catalog.suite.priorityPacketHeading,
      operatorNextStep: catalog.suite.operatorNextStepHeading,
      evidenceGates: catalog.suite.evidenceGatesHeading,
      evidenceGatesSummary: catalog.suite.evidenceGatesSummary,
      verifiedScopeNavigator: catalog.suite.verifiedScopeHeading,
      jumpToSourcePage: catalog.common.jumpToSourcePage,
      openLatestCapturedPage: catalog.common.openLatestCapturedPage,
      loadingDetection: catalog.common.loadingDetection,
      loadingActivity: catalog.common.loadingActivity,
      loadingOutput: catalog.common.loadingOutput,
      loadingRoute: catalog.common.loadingRoute,
      loadingQueue: catalog.common.loadingQueue,
    },
  };
}
